### ISSUE TITLE
Rozšíření výsledků

### ISSUE THREAD

**Issue by padak** [keboola/ex-snowflake-query-history#4]
Snowflake začal počítat data transfer. Oproti existující [query](https://github.com/keboola/ex-snowflake-query-history/blob/e6591b690ab98ecce2a0c037f283a9937f0875ae/src/Keboola/SnowflakeQueryHistory/Fetcher.php#L34) to vrací ještě `OUTBOUND_DATA_TRANSFER_CLOUD`,`OUTBOUND_DATA_TRANSFER_REGION`,`OUTBOUND_DATA_TRANSFER_BYTES`

Bylo by super to tam přidat.

**Comment by Halama** [comment]
Mělo by to tam být https://connection.keboola.com/admin/projects/258/jobs/441235345

**Comment by padak** [comment]
Díky moc!
